services:
  mkcert:
    image: vishnunair/docker-mkcert:latest
    volumes:
      - certs:/certs
      - ./mkcert.sh:/mkcert.sh
    environment:
      - domain=grafana.internal *.internal
    command: sh /mkcert.sh

  traefik:
    image: traefik:v3.5
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:8080:8080"
    environment:
      TRAEFIK_API_DASHBOARD: true
      TRAEFIK_API_INSECURE: true
    volumes:
      - certs:/etc/traefik/certs:ro
      - ./static.yml:/etc/traefik/static.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./acme.json:/etc/traefik/acme.json:rw
    networks:
      internal:
        ipv4_address: 172.20.0.198
    command: --configFile=/etc/traefik/static.yml
    depends_on:
      mkcert:
        condition: service_completed_successfully

  grafana:
    image: grafana/grafana:latest
    networks:
      internal:
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.internal
      - GF_SERVER_DOMAIN=grafana.internal
    volumes:
      - grafana:/var/lib/grafana

  app:
    image: nginx:alpine
    networks:
      internal:

  wireguard:
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Bangkok
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=laptop,phone,tablet
      - PEERDNS=172.20.0.199
      - INTERNAL_SUBNET=10.8.0.0
      - ALLOWEDIPS=10.8.0.0/24,172.20.0.0/24
    volumes:
      - ./wireguard:/config
    ports:
      - "51822:51820/udp"
    sysctls:
      # TODO: Is this necessary?
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      internal:
        ipv4_address: 172.20.0.200

  coredns:
    image: coredns/coredns:latest
    volumes:
      - ./coredns/Corefile:/Corefile:ro
      - ./coredns/db.internal:/db.internal:ro
    networks:
      internal:
        ipv4_address: 172.20.0.199
    command: -conf /Corefile

networks:
  internal:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  grafana:
  certs:
