http:
  routers:
    # App1 - with Let's Encrypt
    app1:
      rule: "Host(`app1-91-108-122-249.nip.io`)"
      entryPoints:
        - web
        - websecure
      tls:
        certResolver: letsencrypt
      service: app1

    # App2 - with self-signed cert
    app2:
      rule: "Host(`app2-91-108-122-249.nip.io`)"
      entryPoints:
        - web
        - websecure
      tls: {}
      service: app2

  services:
    app1:
      loadBalancer:
        servers:
          - url: "http://app1:80"

    app2:
      loadBalancer:
        servers:
          - url: "http://app2:80"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
