http:
  routers:
    app1-http:
      rule: "Host(`app1-91-108-122-249.nip.io`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: app1

    app1-https:
      rule: "Host(`app1-91-108-122-249.nip.io`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: app1

    app2-http:
      rule: "Host(`app2-91-108-122-249.nip.io`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: app2

    app2-https:
      rule: "Host(`app2-91-108-122-249.nip.io`)"
      entryPoints:
        - websecure
      tls: {}
      service: app2

  services:
    app1:
      loadBalancer:
        servers:
          - url: "http://app1:80"

    app2:
      loadBalancer:
        servers:
          - url: "http://app2:80"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  certificates:
    - certFile: /certs/app2-91-108-122-249.nip.io.crt
      keyFile: /certs/app2-91-108-122-249.nip.io.key
